### ISSUE TITLE
gtf_file.txt is empty

### ISSUE THREAD

**Issue by josuebarrera** [Evolinc/RMTA#10]
Hello, I just used RMTAv2.1 on the Discovery Environment.

After the job finished I realized that the GTF file is empty. The BAM files obtained from Hisat2 are perfectly fine though. I just checked the stderr log and found the typical StringTie usage output, followed by an error in the "stringtie --merge" command, saying that the input files were not provided. I think there is a problem in the pipeline (maybe a typo?) that prevents StringTie from running correctly. This prevents the merging step since the initial GTF files were never created.

Best regards,

Josué.

**Comment by andrew-d-l-nelson** [comment]
Hey, can you email me with details about the species you are examining? These issues usually have something to do with the input GTF but I would like to see your case!

**Comment by josuebarrera** [comment]
Thanks Andrew, I'll send you an email.
