### ISSUE TITLE
Failure in mapping

### ISSUE THREAD

**Issue by scho92** [Evolinc/RMTA#16]
Hi

I do not own fancy computer to run RMTA, so I am using CYVERSE DE to run the program (v2.6.3). I tried to map my reads with Grch38 (https://www.ncbi.nlm.nih.gov/genome/guide/human/), but it fails me with the message <Could not locate a HISAT2 index corresponding to basename "ref_genome">. The only difference I see between my run and your example is that my reference genome and annotation files are in fna.gz and gff.gz format. Does not your program supports zipped format as a reference file? I cannot find any other clue that may caused this problem. Would you please help me with the issue?

Best regards,
Seonggeon Cho

**Comment by scho92** [comment]
I extracted reference files and rerun the RMTA. RMTA successfully mapped my reads but with empty feature_counts.txt file. What might have gone wrong?

**Comment by andrew-d-l-nelson** [comment]
Sorry about the delay (holiday in the US). It sounds like you might not have called the feature type correctly. Could you share your analysis with me (in the DE) by sharing with user andrewnelson (at either Boyce Thompson or University of Arizona).

In short, your gene attribute type is probably wrong (either gene_id or ID). I will be able to tell when you share it with me.

**Comment by scho92** [comment]
Dear Andrew Nelson

Thank you for your reply. I shared analysis with you.

Best regards,
Seonggeon Cho

**Comment by andrew-d-l-nelson** [comment]
Hi Seonggeon,
In the "Gene Attribute" box, type "ID" (without quotes) instead of gene_id. The gene attribute (from Featurecounts) is asking for whatever the 9th column starts with. In some GFFs this is "gene_id" and some it is "ID". For the human gff you are using it is "ID".

Good luck!
